name = "nocht-search-ui"
type = "webpack"
account_id = "096741b832c1e787ae5155662146cadd"
workers_dev = true

[site]
bucket = "./build"
entry-point = "workers-site"

[env.production]
# The ID of your domain you're deploying to
zone_id = "9945ff94e7c058af427aa74780c11d33"
# The route pattern your Workers application will be served at
route = "nocht.io/*"
